package barbosshouse.io;

public enum OrdersFactoryTypesEnumeration {
    ORDINARY_ORDERS_FACTORY,
    TEXT_FILE_BASED_ORDERS_FACTORY,
    BINARY_FILE_BASED_ORDERS_FACTORY,
    SERIALIZED_FILE_BASED_ORDERS_FACTORY,
    SOCKET_BASED_ORDERS_FACTORY;
}
